// Generated by CoffeeScript 1.8.0
var URL, background, createJoin, global,
  __slice = [].slice;

URL = {
  BASE: 'http://spurt.elasticbeanstalk.com',
  CREATE: 'http://spurt.elasticbeanstalk.com/link-posts/create',
  EDIT: 'http://spurt.elasticbeanstalk.com/link-posts/edit',
  PUBLISH: 'http://spurt.elasticbeanstalk.com/link-posts/publish'
};

createJoin = function(n, callback) {
  var kwargs;
  kwargs = {};
  return function(arg) {
    _.extend(kwargs, arg);
    if (--n <= 0) {
      return callback.call({}, kwargs);
    }
  };
};

background = chrome.extension.getBackgroundPage();

global = {};

global.uuid = 1;

chrome.tabs.getSelected(function(tab) {
  global.url = tab.url;
  return background.run(function() {
    return $.post(URL.CREATE, {
      uuid: uuid,
      url: url
    }, function() {
      var args;
      args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      return console.log(args);
    });
  });
});
