// Generated by CoffeeScript 1.8.0
var BUTTON_THROTTLE, URL, background, create, createJoin, global, joinSave, onPublish, p, save, setStatus,
  __slice = [].slice;

p = console.log.bind(console);

createJoin = function(n, callback) {
  var kwargs;
  kwargs = {};
  return function(arg) {
    _.extend(kwargs, arg);
    if (--n <= 0) {
      return callback.call({}, kwargs);
    }
  };
};

URL = {
  BASE: 'http://spurt.elasticbeanstalk.com',
  CREATE: 'http://spurt.elasticbeanstalk.com/link-posts/create',
  EDIT: 'http://spurt.elasticbeanstalk.com/link-posts/edit',
  PUBLISH: 'http://spurt.elasticbeanstalk.com/link-posts/publish'
};

BUTTON_THROTTLE = 3000;

background = chrome.extension.getBackgroundPage();

global = {
  publish: false,
  requests: 0
};

global.uuid = 'spades test uuid';

setStatus = function(status) {
  return $('.status').text(status);
};

create = function() {
  return $.post(URL.CREATE, {
    uuid: global.uuid,
    url: global.url
  }, function(res) {
    global.id = JSON.parse(res).id;
    return joinSave();
  });
};

save = function() {
  var url;
  console.log('save');
  console.log('publish', global.publish);
  global.requests += 1;
  if (global.publish) {
    url = URL.PUBLISH;
  } else {
    url = URL.EDIT;
  }
  return $.post(url, {
    uuid: global.uuid,
    id: global.id,
    title: $('[name=title]').text(),
    description: $('[name=description]').text()
  }, function() {
    var args;
    args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    console.log(args);
    global.requests -= 1;
    if (global.publish) {
      return onPublish();
    } else if (global.requests <= 0) {
      return setStatus('Post Saved!');
    }
  });
};

onPublish = function() {
  setStatus('All Done!');
  $('div:not(.status-container)').slideUp();
  return setTimeout(window.close.bind(window), 2500);
};

joinSave = createJoin(2, save);

chrome.tabs.getSelected(function(tab) {
  global.url = tab.url;
  return create();
});

$(document).ready(function() {
  var clicked, throttled;
  throttled = _.throttle((function() {
    var clicked;
    if (global.id) {
      return save();
    } else if (!clicked) {
      clicked = true;
      return joinSave();
    }
  }), BUTTON_THROTTLE);
  clicked = false;
  $('#save').click(function() {
    if (!global.publish) {
      setStatus('Saving...');
    }
    return throttled();
  });
  return $('#publish').click(function() {
    setStatus('Posting...');
    global.publish = true;
    return throttled();
  });
});
